### ISSUE TITLE
Cookiecutter Binder unable to initialize session

### ISSUE THREAD

**Issue by charlesbluca** [pangeo-data/cookiecutter-pangeo-binder#14]
When I create a my own Binder using this Cookiecutter, I get the following error log which ends the session initialization:

![image](https://user-images.githubusercontent.com/20627856/64037288-3ed5be80-cb23-11e9-83ee-1898c9fd0b08.png)

Has the installation method for `intake-xarray` changed since the Cookiecutter has been updated?

**Comment by andersy005** [comment]
It's likely that the error is due to this line

https://github.com/pangeo-data/cookiecutter-pangeo-binder/blob/e7be3a51715dcf2f2a55905f1fe00e1bdc245f21/%7B%7Bcookiecutter.project_slug%7D%7D/binder/environment.yml#L11

My speculation is that specifying a package as it is done above used to work and recent versions of `conda` may have changed how they parse the environment.yml.

**Comment by andersy005** [comment]
@jhamman, do you remember why the `intake` channel was preferred to ` conda-forge` here?

**Comment by jhamman** [comment]
I don't think intake-xarray was in conda forge at the time this repo was built. Bottom line, we need to update this repo a bit (see #11).
